log:
  # 日志级别 5为debug级
  level: 5
proxy:
  # 代理服务监督地址
  host: 0.0.0.0
  # http代理监听端口
  manualPort: 8080
  # 透明代理监听端口
  transparentPort: 8081
  # 线程控制，默认开启1000个线程
  threads: 1000
  # 上游代理设置，支持http、sock5、socks5h协议
  #upstream: http://127.0.0.1:8081
ca:
  # 代理服务中间人CA证书
  cert: config/ca/ca.crt
  # 代理服务中间人CA私钥
  key: config/ca/ca.key
switch:
  # http嗅探开关
  http: true
  # websocket嗅探开关
  websocket: true
  # tcp嗅探开关
  tcp: true
tls:
  # 默认sni，当客户端clienthello没有设置sni时，会使用这个配置下的默认sni进行设置
  defaultSNI: "*.baidu.com"