host: 0.0.0.0
port: 8084
#cert: examples/printer/cert.pem
cert: examples/printer/cacert.pem
#key: examples/printer/key.pem
key: examples/printer/cakey.pem
#san: www.baidu.com
proxy: socks5h://127.0.0.1:10808